AB#264 Prepare endpoint for searching posts
fiit-tp7-2023/tokengram-be pull request #12
Opened 2024-04-03 20:11 UTC by steboee

… endpoint

2024-04-03 21:07 UTC, brano-hozza requested changes

2024-04-03 21:07 UTC, brano-hozza commented on Controllers/RecommendationController.cs
> +        }
Move this to post controller and remove this controller

2024-04-03 21:07 UTC, brano-hozza commented on Database/Neo4j/Nodes/NFTNode.cs
> +
Why we are we not using the same convention for naming_

2024-04-03 21:07 UTC, brano-hozza commented on Services/AuthService.cs
> +            IOptions<JWTOptions> jWTOptions,
rename to jwtOptions

2024-04-04 09:19 UTC, kikz0rsk requested changes

2024-04-04 09:19 UTC, kikz0rsk commented on Services/RecommendationService.cs
> +                    var FixeduserVector = CosineSimilarityUtil.ParseVector(userPreferences);
Use camel case for var names please

2024-04-04 09:19 UTC, kikz0rsk commented on Services/UserService.Vector.cs
> +        }
There's already very similar function `CosineSimiliarityUtil.ParseVector`. Consider using that function and possibly add parameter for specifying separator.

2024-04-08 06:37 UTC, brano-hozza approved these changes

2024-04-08 06:43 UTC, brano-hozza approved these changes

2024-04-08 06:52 UTC, kikz0rsk approved these changes

2024-04-08 06:52 UTC, merged